### ISSUE TITLE
[BUG] 单卡多机微调1.8bchat卡住

### ISSUE THREAD

**Issue by 128Ghe980** [QwenLM/Qwen#1004]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用的 finetune_lora_ds.sh

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

GPUS_PER_NODE=$(python -c 'import torch; print(torch.cuda.device_count())')

NNODES=3

NODE_RANK=0

MASTER_ADDR=${MASTER_ADDR:-localhost}

MASTER_PORT=${MASTER_PORT:-6001}

MODEL="/home/lcwt/nlp_train/models/Qwen-1_8B-Chat" # Set the path if you do not want to load from huggingface directly

DATA="/home/lcwt/nlp_train/data/Qwen_data/train_merge.jsonl"
DS_CONFIG_PATH="finetune/ds_config_zero2.json"

function usage() {
    echo '
Usage: bash finetune/finetune_lora_ds.sh [-m MODEL_PATH] [-d DATA_PATH] [--deepspeed DS_CONFIG_PATH]
'
}

while [[ "$1" != "" ]]; do
    case $1 in
        -m | --model )
            shift
            MODEL=$1
            ;;
        -d | --data )
            shift
            DATA=$1
            ;;
        --deepspeed )
            shift
            DS_CONFIG_PATH=$1
            ;;
        -h | --help )
            usage
            exit 0
            ;;
        * )
            echo "Unknown argument ${1}"
            exit 1
            ;;
    esac
    shift
done

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen \
    --num_train_epochs 7 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 512 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed ${DS_CONFIG_PATH}

config没改，用的默认zero2。
服务器是单机8卡4090.
模型是Qwen-1_8B-Chat

运行sh文件后出现：
[2024-01-24 07:21:42,053] torch.distributed.run: [WARNING] 
[2024-01-24 07:21:42,053] torch.distributed.run: [WARNING] *****************************************
[2024-01-24 07:21:42,053] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-01-24 07:21:42,053] torch.distributed.run: [WARNING] *****************************************

然后不动了。如果手动终止，则出现：
  File "/home/lcwt/venvQwen/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 736, in run
    result = self._invoke_run(role)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 871, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 705, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 54, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]

经过漫长等待终于有了报错：
Traceback (most recent call last):
  File "/home/lcwt/venvQwen/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 736, in run
    result = self._invoke_run(role)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 871, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 705, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 549, in _rendezvous
    workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 637, in _assign_worker_ranks
    role_infos = self._share_and_gather(store, group_rank, group_world_size, spec)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 674, in _share_and_gather
    role_infos_bytes = store_util.synchronize(
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 64, in synchronize
    agent_data = get_all(store, rank, key_prefix, world_size)
  File "/home/lcwt/venvQwen/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 34, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout

请问还需要下载什么东西吗？

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8.10
- Transformers:4.32.0
- Torch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jklj077** [comment]
现象是多进程初始化就没成功，先看下实际用的分布式配置吧，在torchrun前加`echo $DISTRIBUTED_ARGS`，看下结果。

**Comment by 128Ghe980** [comment]
> 现象是多进程初始化就没成功，先看下实际用的分布式配置吧，在torchrun前加`echo $DISTRIBUTED_ARGS`，看下结果，master address是不是localhost

好的我试试

**Comment by 128Ghe980** [comment]
> 现象是多进程初始化就没成功，先看下实际用的分布式配置吧，在torchrun前加`echo $DISTRIBUTED_ARGS`，看下结果，master address是不是localhost

master address是localhost，这是输出：
![qwen_echo](https://github.com/QwenLM/Qwen/assets/44698199/54c0c296-6036-4abf-8f2d-e91a3ad2a610)

**Comment by 128Ghe980** [comment]
搞定了，nnodes要默认1，GPUS_PER_NODE改为需要的卡数量，然后再在torchrun前面加3段东西：NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" CUDA_VISIBLE_DEVICES=X,X,X，X是需要的卡号

**Comment by jklj077** [comment]
NCCL_P2P_DISABLE="1" 这个避免设置，多卡训练一般会变慢。如果不设置会卡住的话（加载完模型训练中卡住，不是你之前遇到的这种卡住），需要排查NCCL或硬件问题。
- https://github.com/QwenLM/Qwen/issues/600
- https://github.com/QwenLM/Qwen/issues/963
