### ISSUE TITLE
7B-Chat-Int4 lora 微调报错

### ISSUE THREAD

**Issue by DuBaiSheng** [QwenLM/Qwen#465]
显卡一张3090 24G的。参数model_max_length 设置的1024.
执行finetune_lora_single_gpu.sh 脚步，报CUDA out of memory。
官方不是说7B-chat-int4  lora 训练只需要21.5G 嘛。
想用q_lora 微调，但是q_lora报错AttributeError: 'DummyOptim' object has no attribute 'step'。
任务需求长度不能再缩了，有别的解决办法吗？

**Comment by Originhhh** [comment]
量化模型无法微调吧

**Comment by DuBaiSheng** [comment]
> 量化模型无法微调吧

官方文档里面写了 微调只能量化的微调，非量化的不能微调

**Comment by deepthman** [comment]
7B用qlora最低9G就能微调了

**Comment by DuBaiSheng** [comment]
> 7B用qlora最低9G就能微调了

是的，但是代码微调报错。。。

**Comment by DuBaiSheng** [comment]
> 7B用qlora最低9G就能微调了

你用q_lora 微调成功了吗

**Comment by deepthman** [comment]
> > 7B用qlora最低9G就能微调了
> 
> 你用q_lora 微调成功了吗

我微调没问题啊，主要就是把flask_attn给卸了，用上deepspeed，都很正常。有flask_attn就会一直报错。

**Comment by DuBaiSheng** [comment]
> > > 7B用qlora最低9G就能微调了
> > 
> > 
> > 你用q_lora 微调成功了吗
> 
> 我微调没问题啊，主要就是把flask_attn给卸了，用上deepspeed，都很正常。有flask_attn就会一直报错。

我没装flash-attention， 但还是有问题，那可能是我这边的问题，谢谢。

**Comment by Bonnyjwj** [comment]
> > > > 7B用qlora最低9G就能微调了
> > > 
> > > 
> > > 你用q_lora 微调成功了吗
> > 
> > 
> > 我微调没问题啊，主要就是把flask_attn给卸了，用上deepspeed，都很正常。有flask_attn就会一直报错。
> 
> 我没装flash-attention， 但还是有问题，那可能是我这边的问题，谢谢。

你好，请问这个问题解决了么？我也遇到了一样的问题，报错AttributeError: 'DummyOptim' object has no attribute 'step'
😥

**Comment by jklj077** [comment]
@DuBaiSheng @Bonnyjwj 是用的finetune_qlora_single_gpu.sh这个脚本吗？这个报错可能跟特定的transformers版本有关（单卡由于某些原因也用了DeepSpeed，但DeepSpeed未成功初始化），可以尝试升级transformers以及相关库（如accelerator）或者试试改下启动命令，把`python`改成`python -m torch.distributed.launch --nproc_per_node 1`或者`torchrun --nproc_per_node 1` 。

**Comment by DuBaiSheng** [comment]
> > > > > 7B用qlora最低9G就能微调了
> > > > 
> > > > 
> > > > 你用q_lora 微调成功了吗
> > > 
> > > 
> > > 我微调没问题啊，主要就是把flask_attn给卸了，用上deepspeed，都很正常。有flask_attn就会一直报错。
> > 
> > 
> > 我没装flash-attention， 但还是有问题，那可能是我这边的问题，谢谢。
> 
> 你好，请问这个问题解决了么？我也遇到了一样的问题，报错AttributeError: 'DummyOptim' object has no attribute 'step' 😥

没解决，，

**Comment by DuBaiSheng** [comment]
> @DuBaiSheng @Bonnyjwj 是用的finetune_qlora_single_gpu.sh这个脚本吗？这个报错可能跟特定的transformers版本有关（单卡由于某些原因也用了DeepSpeed，但DeepSpeed未成功初始化），可以尝试升级transformers以及相关库（如accelerator）或者试试改下启动命令，把`python`改成`python -m torch.distributed.launch --nproc_per_node 1`或者`torchrun --nproc_per_node 1` 。

是用的finetune_qlora_single_gpu.sh。我用的transformer版本是4.32 的，你提供的两个启动命令我都试了，还是不行。然后我重新装了一个环境，执行finetune_qlora_single_gpu.sh，又有新的错误，  assert self.qweight.device.type == "cuda"。

**Comment by jklj077** [comment]
> 是用的finetune_qlora_single_gpu.sh。我用的transformer版本是4.32 的，你提供的两个启动命令我都试了，还是不行。然后我重新装了一个环境，执行finetune_qlora_single_gpu.sh，又有新的错误， assert self.qweight.device.type == "cuda"。

@DuBaiSheng 您好，新的环境中，transformers的版本还是4.32吗？请提供下相关的软件版本以及完整的错误报告哈。

**Comment by DuBaiSheng** [comment]
> > 是用的finetune_qlora_single_gpu.sh。我用的transformer版本是4.32 的，你提供的两个启动命令我都试了，还是不行。然后我重新装了一个环境，执行finetune_qlora_single_gpu.sh，又有新的错误， assert self.qweight.device.type == "cuda"。
> 
> @DuBaiSheng 您好，新的环境中，transformers的版本还是4.32吗？请提供下相关的软件版本以及完整的错误报告哈。

是4.32。这是脚本
<img width="491" alt="image" src="https://github.com/QwenLM/Qwen/assets/35100324/39d99c53-158a-448e-88a3-85b368601c44">
这是执行脚本错误。
![image](https://github.com/QwenLM/Qwen/assets/35100324/8612daca-a036-4079-a67b-0ecf9c6e5284)

**Comment by jklj077** [comment]
请尝试降级AutoGPTQ版本至低于0.5.0，比如0.4.2。

**Comment by DuBaiSheng** [comment]
> 请尝试降级AutoGPTQ版本至低于0.5.0，比如0.4.2。

运行finetune_qlora_single_gpu.sh之前的错误没了，但是出现新的问题，报CUDA out of memory。我卡是3090的 24G，我训练的参数设置的很小。
<img width="583" alt="image" src="https://github.com/QwenLM/Qwen/assets/35100324/6d9ef5a9-a558-45e8-b0f5-ce12dd064b34">
运行finetune_lora_single_gpu.sh脚本，我设置model_max_length =512，都能运行。

**Comment by jklj077** [comment]
qlora显存占用比lora高是异常的情况，问题排查：
- 未运行脚本时，显存占用情况
- 仅加载模型、训练未开始时，显存占用情况：是否加载后已经占用了超出预期的显存
- 最好能够提供cuda pytorch transformers accelerate optimum autogptq deepspeed等的版本或安装方式，或者其它有利于复现的信息

**Comment by jklj077** [comment]
> 仅加载模型、训练未开始时，显存占用情况20G。

根据未训练时的显存占用，似乎是加载了未量化的模型，可以确认下加载的是int4模型吗（模型文件夹中的safetensors文件一共多大）？

**Comment by DuBaiSheng** [comment]
> > 仅加载模型、训练未开始时，显存占用情况20G。
> 
> 根据未训练时的显存占用，似乎是加载了未量化的模型，可以确认下加载的是int4模型吗（模型文件夹中的safetensors文件一共多大）？

模型是从huggingface 下载的Qwen/Qwen-7B-Chat-Int4。 safetensors 一共三个文件差不多，5.8G
<img width="543" alt="image" src="https://github.com/QwenLM/Qwen/assets/35100324/9d52a977-c926-4d52-bdce-6da5e6573696">
这个

**Comment by jklj077** [comment]
Hi, if possible, could you please try using the docker image provided to rule out the environment issues?
