### ISSUE TITLE
在两张A40显卡上微调报错  NCCL超时

### ISSUE THREAD

**Issue by 1424153694** [QwenLM/Qwen#531]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior
```
Loading extension module fused_adam...
Time to load fused_adam op: 0.5319623947143555 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.5037925243377686 seconds


[E ProcessGroupNCCL.cpp:474] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=778567680, NumelOut=778567680, Timeout(ms)=1800000) ran for 1800047 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:474] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=778567680, NumelOut=778567680, Timeout(ms)=1800000) ran for 1800110 milliseconds before timing out.
/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py:96: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = get_accelerator().IntTensor([0])
/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:915] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=778567680, NumelOut=778567680, Timeout(ms)=1800000) ran for 1800110 milliseconds before timing out.
[2023-10-25 18:48:46,111] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 8517 closing signal SIGTERM
[2023-10-25 18:48:48,780] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 8518) of binary: /root/miniconda3/envs/Qwen-14b/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/Qwen-14b/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/Qwen-14b/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
finetune.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-25_18:48:46
  host      : autodl-container-bac311933c-8629fe1b
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 8518)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 8518
=====================================================
```
### 期望行为 | Expected Behavior

微调成功

### 运行环境 | Environment

```Markdown
- OS:Linux
- Python:3.8
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
可能读模型或者读数据时间太长了，就超时了（默认是半小时）。现在用的本地模型文件吗？如果是因为模型下载太慢，这个check可以关掉或者设置得更长。

**Comment by 1424153694** [comment]
> 可能读模型或者读数据时间太长了，就超时了（默认是半小时）。现在用本地模型文件吗？如果是因为模型下载太慢，这个检查可以关掉或者设置得更长。

是在学校服务器上跑的，用的本地模型文件，测试的数据只有几条，但还是会报超时，请问您了解这是什么原因吗

**Comment by jklj077** [comment]
这个不了解了，如果不是因为其它IO操作慢的话（比如加载checkpoint、保存checkpoint、加载数据），NCCL问题很不好debug。跟硬件支持、软件环境配置都可能有关，这个可能得找需要找你们的系统管理员了，看看你们系统得怎么配置。

**Comment by Fire-Star** [comment]
这个可能是由很多原因导致，我遇到过这个问题，我那台机器解决的方式是将linux内核版本从5.4.0升级到5.5.0。

你的错误信息也不完整，可以再从头看看错误。

**Comment by dwq370** [comment]
ds_report检查 fused_adam ............. [NO] ...... [OKAY] ，直接升级内核能解决？

**Comment by SmallZhangZhang** [comment]
> ds_report检查 fused_adam ............. [NO] ...... [OKAY] ，直接升级内核能解决？

请问你的这个问题解决了吗？如果解决了，是怎样操作的呢
