### ISSUE TITLE
[BUG] Google Colab 上运行首页提供的代码报错

### ISSUE THREAD

**Issue by Raychanan** [QwenLM/Qwen#547]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

感谢你们的工作！

报错显示`AssertionError: libcuda.so cannot found!`

代码直接从当前项目的首页复制粘贴的，没有做任何改动。GPU 使用的 V100。在 Google 和 Issues 里面直接搜`libcuda.so`没有找到相关的解决方案。

代码见 [Colab Notebook](https://colab.research.google.com/drive/1wsmumdgSaURbq4ipPtBDINBrQdzGls1z?usp=sharing)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
我们检查了colab链接中错误报告，请先卸载`flash-attn`试试能否运行（或尝试降级至`v2.1.1`版本及以下）。

```
!pip uninstall flash-attn
```

**Comment by Raychanan** [comment]
确实解决了。谢谢！

**Comment by koking0** [comment]
> 我们检查了colab链接中错误报告，请先卸载`flash-attn`试试能否运行（或尝试降级至`v2.1.1`版本及以下）。
> 
> ```
> !pip uninstall flash-attn
> ```

为什么会有这个问题呢？如果就想用Flash Attention呢？
