### ISSUE TITLE
双显卡，两张3090显卡，全精度推理， CUDA out of memory

### ISSUE THREAD

**Issue by jichaosun001** [QwenLM/Qwen#625]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

两张3090显卡，用官方脚本推理对话，对话轮次三四轮后，出现
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 16.19 MiB is free. Including non-PyTorch memory, this process has 23.66 GiB memory in use. Of the allocated memory 22.34 GiB is allocated by PyTorch, and 207.43 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

实际上其中一张目前只占用了大概6G，24G显存还有很多没用

### 期望行为 | Expected Behavior

两张显卡显存可以平分，不是一张满了，另外一张还比较空

### 复现方法 | Steps To Reproduce

readme中的推理脚本，再加两三轮

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3。9
- Transformers:4.27.1
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jichaosun001** [comment]
![image](https://github.com/QwenLM/Qwen/assets/32610812/82e19414-49be-4aee-b3e4-35372431a437)

**Comment by jklj077** [comment]
由于您已在<https://github.com/QwenLM/Qwen/issues/450>中表示相关问题已解决，本issue先关闭了。
