### ISSUE TITLE
[BUG] <一机多卡V100lora微调卡住>

### ISSUE THREAD

**Issue by yoohhwz** [QwenLM/Qwen#963]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在使用官方多gpu代码微调时遇到如下错误：bash finetune/finetune_lora_ds.sh
--nproc_per_node 2 --nnodes 1 --node_rank 0 --master_addr localhost --master_port 6001

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2024-01-15 10:46:03,790] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-15 10:46:03,815] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-15 10:46:05,527] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-01-15 10:46:05,527] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-01-15 10:46:05,555] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-01-15 10:46:05,555] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
The model is automatically converting to fp16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
The model is automatically converting to fp16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 8/8 [00:53<00:00,  6.67s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 8/8 [01:02<00:00,  7.80s/it]

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/data/anaconda3/envs/qwen-7b/lib/libcudart.so'), PosixPath('/data/anaconda3/envs/qwen-7b/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /data/anaconda3/envs/qwen-7b/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
/data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/data/anaconda3/envs/qwen-7b/lib/libcudart.so.11.0'), PosixPath('/data/anaconda3/envs/qwen-7b/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /data/anaconda3/envs/qwen-7b/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
/data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /data/anaconda3/envs/qwen-7b/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
trainable params: 143,130,624 || all params: 7,864,455,168 || trainable%: 1.8199687192876373
Loading data...
Formatting inputs...Skip in lazy mode
trainable params: 143,130,624 || all params: 7,864,455,168 || trainable%: 1.8199687192876373
trainer.train()
trainer.train()
```
然后就是多达2天的卡住

### 复现方法 | Steps To Reproduce

1. finetune.py中device_map = None
2. finetune_lora_ds.sh中 --bf16 False
然后执行 bash finetune/finetune_lora_ds.sh 后就卡住

### 运行环境 | Environment

```Markdown
- OS:20.04.1
- Python:3.10.13
- Transformers:4.32.0
- PyTorch:1.13.1+cu117
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by jklj077** [comment]
1. 微调的什么模型
2. 提供的日志里有大量bnb内容，不符合预期，是否有开启load_in_4bits之类的
3. 根据bnb提示，环境已经坏了，同时有cuda 11和cuda 12

**Comment by yoohhwz** [comment]
> 1. 微调的什么模型
> 2. 提供的日志里有大量bnb内容，不符合预期，是否有开启load_in_4bits之类的
> 3. 根据bnb提示，环境已经坏了，同时有cuda 11和cuda 12的运行时

1、微调的7B
2、finetune.py文件中load_in_4bit=True未做改变
3、因为机器上还有其他项目在跑，不清楚两个cuda是否影响这个卡住的情况

**Comment by jklj077** [comment]
> finetune.py文件中load_in_4bit=True未做改变

请检查下finetune.py与本repo中当前版本是否一致哈。

**Comment by yoohhwz** [comment]
> > finetune.py文件中load_in_4bit=True未做改变
> 
> 请检查下finetune.py与本repo中当前版本是否一致哈。

repo中requirements中已经指明的版本是一致的，请问还有其他问题解决可能吗？

**Comment by jklj077** [comment]
指finetune.py的内容哈（文件版本），finetune.py里不应该有load_in_4bit=True

**Comment by yoohhwz** [comment]
> refers to the content of the finetune.py (file version), and there should be no load_in_4bit=True in the finetune.py

哎呀   行   我试试最新的finetune.py代码

**Comment by mru4913** [comment]
@yoohhwz 
你的v100如果下载flash atten？

**Comment by yoohhwz** [comment]
> @yoohhwz 你的v100如果下载flash atten？

我没用flash atten ，之前试了一下好像不行就没有再用了，毕竟那是优化，不是必须

**Comment by PineappleWill** [comment]
> > refers to the content of the finetune.py (file version), and there should be no load_in_4bit=True in the finetune.py
> 
> 哎呀 行 我试试最新的finetune.py代码

请问后面解决了么？我也碰到了卡住的问题
